imports:
    - { resource: config.yml }
    - { resource: "@ApiMockBundle/Resources/config/services.yml" }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

parameters:
    hosts.local: http://localhost:8000

api:
    github:
        urls:
            site: "%hosts.local%/mock/github/"
            api:  "%hosts.local%/mock/github/"
        client_id: "random-id"
        client_secret: "this-is-not-secret"

api_mock:
    buzz:
        localforward:
            localhost: "%hosts.local%"

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]

