imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ApiBundle/Resources/config/services.yml" }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    templating:
        engines: ['twig']
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    php_errors:
        log: true
    validation:
        enabled: true
        enable_annotations: true
    form:
        enabled: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine:
    dbal:
        driver:   "pdo_mysql"
        host:     "%database.host%"
        dbname:   "%database.name%"
        user:     "%database.user%"
        password: "%database.password%"

    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true

api:
    github:
        urls:
            site: "%github.urls.site%"
            api:  "%github.urls.api%"
        client_id: "%github.client_id%"
        client_secret: "%github.client_secret%"
    golive:
        urls:
            site: "%golive.urls.site%"
            api:  "%golive.urls.api%"
        stage: preprod

jms_serializer:
    metadata:
        auto_detection: true
