imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    templating:
        engines: ['twig']
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    php_errors:
        log: true
    serializer:
        enabled: true
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine:
    dbal:
        driver:   pdo_sqlite
        charset:  UTF8
        path:     "%kernel.root_dir%/../var/database.sqlite"

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

app:
    github:
        urls:
            site: "%github.urls.site%"
            api:  "%github.urls.api%"
        client_id: "%github.client_id%"
        client_secret: "%github.client_secret%"
