imports:
    - { resource: config.yml }
    - { resource: "@ApiMockBundle/Resources/config/services.yml" }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

api:
    github:
        urls:
            site: "http://goprod.local/app_dev.php/mock/github/"
            api:  "http://goprod.local/app_dev.php/mock/github/"
        client_id: "random-id"
        client_secret: "this-is-not-secret"

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]

