imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver: pdo_sqlite
        path: '%kernel.root_dir%/../var/database_test.db'
        charset: UTF8

parameters:
    hosts.local: http://localhost:8765

services:
    # Avoid notifications in test env
    # @todo fix this
    notification_bundle.listener.deploy.status.update:
        abstract: true
