api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

app_bundle:
    resource: '@FrontBundle/Resources/config/routing.yml'

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
