security:
    providers:
        db_provider:
            entity:
                class: "ApiBundle\\Entity\\User"
                property: "accessToken"

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - "api_bundle.token_authenticator"
    access_control:
        - { path: ^/api/config$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/auth$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }
