mock_github_user_oauth:
    path: /login/oauth/authorize
    defaults:
        _controller: ApiMockBundle:Github:oauth

mock_github_user_access_token:
    path: /login/oauth/access_token
    defaults:
        _controller: ApiMockBundle:Github:getUser

mock_github_user:
    path: /user
    defaults:
        _controller: ApiMockBundle:Github:getUser

mock_github_issue_search:
    path: /search/issues
    defaults:
        _controller: ApiMockBundle:Github:searchIssues

mock_github_pullrequest:
    path: /repos/{owner}/{repo}/pulls/{number}
    defaults:
        _controller: ApiMockBundle:Github:getPullRequest

mock_github_pullrequest_merge:
    path: /repos/{owner}/{repo}/pulls/{number}/merge
    methods:  [PUT]
    defaults:
        _controller: ApiMockBundle:Github:mergePullRequest

mock_github_issue:
    path: /repos/{owner}/{repo}/issues/{number}
    defaults:
        _controller: ApiMockBundle:Github:getIssue

mock_github_organizations:
    path: /organizations
    defaults:
        _controller: ApiMockBundle:Github:getOrganizations

mock_gitub_search_repositories:
    path: /search/repositories
    defaults:
        _controller: ApiMockBundle:Github:searchRepositories

mock_gitub_delete_reference:
    path: /repos/{owner}/{repo}/git/{ref}
    methods:  [DELETE]
    defaults:
        _controller: ApiMockBundle:Github:deleteReference
    requirements:
        ref: .+
