user_auth:
    path: /user/auth
    defaults:
        _controller: ApiBundle:User:auth

user_profile:
    path: /user/profile
    defaults:
        _controller: ApiBundle:User:profile
    options:
        expose: true

user_chekprofile:
    path: /user/profile/complete
    defaults:
        _controller: ApiBundle:User:checkProfile
    options:
        expose: true

app_config:
    path: /config
    defaults:
        _controller: ApiBundle:Config:config
    options:
        expose: true
