user_auth:
    path: /user/auth
    defaults:
        _controller: ApiBundle:User:auth

user_profile:
    path: /user
    methods:  [GET]
    defaults:
        _controller: ApiBundle:User:profile

user_update:
    path: /user
    methods:  [POST]
    defaults:
        _controller: ApiBundle:User:update

user_chekprofile:
    path: /user/profile/complete
    defaults:
        _controller: ApiBundle:User:checkProfile

app_config:
    path: /config
    defaults:
        _controller: ApiBundle:Config:config

deploy_create:
    path: /deploys
    methods:  [POST]
    defaults:
        _controller: ApiBundle:Deploy:create

deploy_by_current_user:
    path: /user/deploys
    defaults:
        _controller: ApiBundle:Deploy:getByCurrentUser

deploy_by_id:
    path: /deploys/{id}
    defaults:
        _controller: ApiBundle:Deploy:get

deploy_cancel:
    path: /deploys/{id}/cancel
    methods:  [POST]
    defaults:
        _controller: ApiBundle:Deploy:cancel

deploy_confirm:
    path: /deploys/{id}/confirm
    methods:  [POST]
    defaults:
        _controller: ApiBundle:Deploy:confirm

deploy_by_repository:
    path: /{owner}/{repository}/deploys
    defaults:
        _controller: ApiBundle:Deploy:getByRepository
