user_auth:
    path: /user/auth
    defaults:
        _controller: ApiBundle:User:auth

user_profile:
    path: /user
    methods:  [GET]
    defaults:
        _controller: ApiBundle:User:profile
    options:
        expose: true

user_update:
    path: /user
    methods:  [POST]
    defaults:
        _controller: ApiBundle:User:update
    options:
        expose: true

user_chekprofile:
    path: /user/profile/complete
    defaults:
        _controller: ApiBundle:User:checkProfile
    options:
        expose: true

app_config:
    path: /config
    defaults:
        _controller: ApiBundle:Config:config
    options:
        expose: true

deploy_create:
    path: /deploys
    methods:  [POST]
    defaults:
        _controller: ApiBundle:Deploy:create
    options:
        expose: true

deploy_by_current_user:
    path: /user/deploys
    defaults:
        _controller: ApiBundle:Deploy:getByCurrentUser
    options:
        expose: true
