services:
    # Doctrine repositories
    api_bundle.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        abstract: true

    api_bundle.repository.user:
        parent: api_bundle.repository
        arguments:
            - "ApiBundle\\Entity\\User"

    api_bundle.repository.deploy:
        parent: api_bundle.repository
        arguments:
            - "ApiBundle\\Entity\\Deploy"

    # Listeners
    api_bundle.listener.github.user.login:
        class: "ApiBundle\\Listener\\User\\UserLogin"
        arguments:
            - "@api_bundle.repository.user"
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: "kernel.event_listener"
                event: "github.client.user.login"
                method: "onUserLogin"

    api_bundle.listener.kernel.view:
        class: "ApiBundle\\Listener\\Kernel\\KernelView"
        arguments:
            - "@serializer"
        tags:
            -
                name: "kernel.event_listener"
                event: "kernel.view"
                method: "onKernelView"

    # Misc
    api_bundle.serializer.form.error:
        class: "ApiBundle\\Form\\Serializer\\ErrorsSerializer"

    api_bundle.github_client:
        class: "ApiBundle\\Service\\Github\\Client"
        arguments:
            - "@buzz"
            - "%api_bundle.github.urls.site%"
            - "%api_bundle.github.urls.api%"
            - "%api_bundle.github.client_id%"
            - "%api_bundle.github.client_secret%"
            - ~
            - "@event_dispatcher"
