<?php

namespace ApiBundle\Repository;

/**
 * DeployRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeployRepository extends \Doctrine\ORM\EntityRepository
{
}
