index:
  path: /
  defaults:
    _controller: AppBundle:Front:index

auth:
  path: /auth
  defaults:
    _controller: AppBundle:User:auth

chekprofile:
  path: /check_profile
  defaults:
    _controller: AppBundle:User:checkProfile
