services:
  app_bundle.github_client:
    class: "AppBundle\\Service\\Github\\Client"
    arguments:
      - "@buzz"
      - "%app_bundle.github.url%"
      - "%app_bundle.github.client_id%"
      - "%app_bundle.github.client_secret%"
