services:
    app_bundle.repository.user:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - "AppBundle\\Entity\\User"

    app_bundle.github_client:
        class: "AppBundle\\Service\\Github\\Client"
        arguments:
            - "@buzz"
            - "%app_bundle.github.urls.site%"
            - "%app_bundle.github.urls.api%"
            - "%app_bundle.github.client_id%"
            - "%app_bundle.github.client_secret%"
            - ~
            - "@event_dispatcher"

    app_bundle.listener.github.user.login:
        class: "AppBundle\\Listener\\User\\UserLogin"
        arguments:
            - "@app_bundle.repository.user"
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: "kernel.event_listener"
                event: "github.client.user.login"
                method: "onUserLogin"
