ApiBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        login:
            expose: true
        name:
            expose: true
        goliveKey:
            expose: true
        hipchatName:
            expose: true
        avatarUrl:
            expose: true
        createDate:
            expose: true
